# Generated by Django 4.2.7 on 2026-02-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('wind_speed', models.FloatField()),
                ('seismic_zone', models.CharField(max_length=10)),
                ('seismic_zone_factor', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
            ],
            options={
                'db_table': 'location_parameters',
                'ordering': ['state', 'city'],
                'unique_together': {('state', 'city')},
            },
        ),
    ]
