# Generated by Django 4.2.7 on 2026-02-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_type', models.CharField(choices=[('highway', 'Highway'), ('other', 'Other')], max_length=20)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_wind_speed', models.FloatField(blank=True, null=True)),
                ('custom_seismic_factor', models.FloatField(blank=True, null=True)),
                ('custom_max_temp', models.FloatField(blank=True, null=True)),
                ('custom_min_temp', models.FloatField(blank=True, null=True)),
                ('span', models.FloatField()),
                ('carriageway_width', models.FloatField()),
                ('footpath', models.CharField(choices=[('single', 'Single-sided'), ('both', 'Both'), ('none', 'None')], max_length=20)),
                ('skew_angle', models.FloatField()),
                ('girder_material', models.CharField(max_length=10)),
                ('bracing_material', models.CharField(max_length=10)),
                ('deck_material', models.CharField(max_length=10)),
                ('girder_spacing', models.FloatField(blank=True, null=True)),
                ('num_girders', models.IntegerField(blank=True, null=True)),
                ('deck_overhang', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bridge_designs',
                'ordering': ['-created_at'],
            },
        ),
    ]
